CLARIAH/grlc

grlc.py
=> Wraps IRI parameter with <>

src/gquery.py
Added a check to ensure 'enumerate' is part of the metadata.
=> Add check for enumerate

README.md
Citable via Zenodo! Closes #85
=> Add Zenodo DOI

src/fileLoaders.py, src/gquery.py, src/utils.py
Added a few validations for better error handling.
=> Added safety validations

src/gquery.py
Fixed loading endpoints from `endpoint.txt`
=> Bugfix from #96

src/static/js/grlc-api.js, src/static/js/grlc-layout.js, src/templates/api-docs.html
Move JS code to separate files, remove unused code, add very short documentation comments.
Closes #124
=> Cleanup JS code

src/gquery.py, src/static/js/grlc-api.js, src/templates/api-docs.html, src/utils.py
=> Fix api routes and try out validation

src/gquery.py, src/server.py, src/utils.py
=> Fix endpoint loading bug

README.md
=> Fix broken link on README.

README.md, src/gquery.py
Getting `dev` to be in sync with `master`
=> Forwarding dev

.travis.yml, .travis/before_deploy.sh, .travis/before_install.sh, CITATION.cff, MANIFEST.in, requirements.txt, setup.py
Tagged releases will automatically get deployed on PyPI.
=> Automatically deploy tagged releases

GrlcFromNotebook.ipynb, requirements.txt, setup.py, src/gquery.py, src/server.py, src/utils.py
-  Make readme pypi friendly
- Update requirements
- Grlc from python demo
=> Dev updates and tutorial

.travis.yml, .travis/before_install.sh, .travis/install.sh, setup.py, src/fileLoaders.py, tests/mock_data.py, tests/test_loaders.py
=> Add travis testing for windows

README.md
=> Update README: install instructions

src/static.py
=> Change lookup path for config.ini

config.default.ini, src/cache.py, src/glogging.py, src/gquery.py, src/projection.py, src/prov.py, src/server.py, src/sparql.py, src/static.py, src/swagger.py, src/utils.py
Make debug configurable via config
=> Debug optional

src/fileLoaders.py, src/utils.py, tests/mock_data.py, tests/repo/url.yml, tests/test_loaders.py
Hola @albertmeronyo,
Aqui te van los cambios del sprint. Ya funcionan los tests, asi que el nuevo FileLoader deberia funcionar sin mucho problema. Mando el PR al branch de `paths` para que lo integres con el nuevo api, y podamos probar todo junto antes de meterlo a `dev`.
Avisame si te puedo ayudar en algo.
Saludos!
=> File loader url

src/fileLoaders.py, src/templates/api-docs.html, src/templates/index.html
=> Use absolute paths to static files

src/server.py, src/static/js/grlc-api.js
Fixes  #255.
We should remove backwards compatibility on the next major release, after some time to transition.
=> Api back compatible

.github/workflows/tweet-release.yml
=> Gh actions

src/swagger.py, src/utils.py
Additional to #284, this PR also fixes the path built to execute grlc queries.
=> Fix bug on <subdir> execution path building

src/pagination.py
=> Pagination links -- fixes #259

src/server.py
=> Backward compatibility of /spec endpoints

docker-assets/entrypoint.sh
Adding an extra check for DEBUG variable on Dockerfile
Fixes #281
=> Docker debug

MANIFEST.in, setup.py, src/__init__.py, src/__version__.py
Version number is updated in a single file (`CITATION.CFF`) -- everything else (`setup.py`, `__init__.py`) read version number from there.
Fixes #266
=> Version management

README.md, src/server.py
As discussed in #277 
Closes #300
=> Remove support for /spec in favour of /swagger

README.md, src/utils.py
Addressing issue described in #313
=> Restrict transform decorator to application/json

requirements.txt
=> Update SPARQLTransformer to 2.1.1

src/fileLoaders.py, src/swagger.py
Fixes #330 -- perhaps a warning should be added for missing license.
=> Add extra check for missing license

requirements.txt
=> Upgrade rdflib 5.0.0

src/fileLoaders.py, tests/repo/url.yml
Implements new feature discussed in #331
=> Adding support for relative urls in spec files

paper.bib, paper.md
Much more can be written on the topic, but this is already covered in the book (to be published) and upcoming survey paper (currently in the planning).
Closes #325
=> Briefly describes state of field

src/gquery.py
Propagate exceptions raised by rdflib parsing. Addresses #352
=> Propagate exceptions raised by rdflib parsing

src/gquery.py
=> Safe yaml loader

src/gquery.py, src/utils.py
Change warnings into debug messages. See #350
=> Warnings to debug messages

Dockerfile, src/utils.py
=> Update docker image to Python 3.8

src/server.py, src/swagger.py, src/utils.py
Relates to #377 and #384 
Since #388 was difficult to merge, this PR incorporates the key changes introduced there.
=> [WIP] Adding SPARQL Update

src/fileLoaders.py, tests/mock_data.py, tests/test_loaders.py
=> Adding mock gilab repo

CONTRIBUTORS.md, src/server.py, src/utils.py
As discussed in #385, SPARQL Transformer already supports JSON-LD generation. This PR uses this functionality.
This fixes #385.
=> Support returning JSON-LD directly

.github/workflows/publish_pypi.yml, .github/workflows/testing.yml, Dockerfile, bin/grlc-server, requirements-test.txt, requirements.txt, src/fileLoaders.py, src/prov.py, src/utils.py, tests/mock_data.py, tests/test_endpoints.py
Update requirements, docker, github actions and small code updates to make compatible with Python versions 3.8 to 3.11, dropping compatibility with previous versions (as per discussion #409)
=> Py versions

.github/workflows/publish_pypi.yml, .github/workflows/testing.yml, Dockerfile, bin/grlc-server, requirements-test.txt, requirements.txt, src/fileLoaders.py, src/gquery.py, src/prov.py, src/utils.py, tests/mock_data.py, tests/test_endpoints.py, tests/test_gquery.py
Change how variables are identified during query rewrite. This allow for replacement for variables inside a function such as FILTER (as raised in #230, #322, #378).
=> Query rewrite

README.md
=> Add explanation of why Google analytics is used

requirements.txt
=> Update requests to 2.32.3

.github/workflows/testing.yml, Dockerfile
=> Drop support for Python 3.8

CITATION.cff, src/server.py
=> Prepare for V1.3.10 release
