CLARIAH/grlc

grlc.py, src/gquery.py
Was having issues replacing parameters on a query using Basil syntax. In particular, was having problems with parameters which do not come from an enum.
More specifically, I was getting errors loading and executing [this](https://github.com/c-martinez/grlc-test/blob/master/basilTest.rq) example query, when I was calling it like this:
```
http://localhost:8088/api/c-martinez/grlc-test/basilTest?year=2000
```
This PR solves the issue and adds the `PREFIX xsd` if required.
=> Add XSD support

src/utils.py
Splitting `build_spec` further, moving some code to new function `process_query_text`. In this way, it is possible to parse the text of a query even if it has not yet been committed to github. This is handy for testing queries before putting them online.
Also, added an `extraMetadata` parameter, which allows to return other metadata which we might be interested on.
=> Added process_query_text and extra metadata

src/gquery.py, src/utils.py
As suggested on #42, changed the `Accept` header so it will support `application/json` or `application/sparql-results+json`.
It turns out that `static.mimetypes` already has support for these headers. However, as they are, I think 
`application/json` is given preference over `application/sparql-results+json`. It doesn't make much difference, but if `application/sparql-results+json` is supposed to be the official accept value, then perhaps it should be given preference.
=> Change 'Accept' header

LICENSE.txt, MANIFEST.in, README.md, setup.cfg, setup.py
Before PR is merged, `pip install git+git://github.com/CLARIAH/grlc` will not work.
Instead, test using:
```
pip install git+git://github.com/c-martinez/grlc.git@pipInstall
```
Once this works, we can add grlc to [pypi](https://pypi.python.org/pypi), and we will be able to install by doing `pip install grlc` ;-)
=> Pip install

config.default.ini, src/gquery.py, src/static.py
One option for hiding sparql endpoints is to have `DEFAULT_ENDPOINT`to be configurable via the `config.ini` file.
This may (at least partially) solve issues #76 and #72 .
=> Make endpoint configurable

config.default.ini, src/fileLoaders.py, src/gquery.py, src/queryTypes.py, src/server.py, src/static.py, src/utils.py
Addressing #80. To use local files:
Set in config.ini the key:
```local_sparql_dir = ./ ```
pointing at the local directory where grlc will look for queries.
Afterwards, run `grlc-server` and on your browser go to `/api/local`. Instead of searching for queries on github/user/repo, grlc will load queries from the specified local folder. For the rest, it works as usual.
=> Serve local queries

README.md
Added a one line intro to what is grlc. We can put the same text on the landing page on zenodo.
=> Add 'what is grlc'

src/gquery.py, src/server.py
Allow to provide endpoint as request url parameter. This overrides default value in config.ini and endpoint parameter on query (`#+ endpoint:`)
```
curl -X GET --header "Accept: application/json" "http://grlc.io/api/user/repo/query?endpoint=http://example.com/sparql"
```
Might be good to document this in a bit more detail.
=> Add endpoint to parameter requests

src/gquery.py, tests/repo/test-enum.rq, tests/test_gquery.py, tests/test_loaders.py
Refering to #114 and replacing #83 
This allows to specify on the header the values available in the enumeration, without querying the sparql endpoint. Header should have the following format:
```
#+ enumerate:
#+   - var:
#+     - value1
#+     - value2
#+     - value3
```
=>  Add explicit enumerations

README.md, src/gquery.py, src/utils.py
Replacing #99. New features:
- `endpoint` parameter can be specified on swagger-ui
- `endpoint` parameter can on swagger-ui has default value (endpoint from decorator, endpoint.txt or default)
- `endpoint` parameter on swagger-ui can be disabled by adding `#+ endpoint_in_url: False` decorator
=> Endpoint url

src/utils.py
According to `https://swagger.io/specification/`, `description` supports markdown.
=> Format description as markdown

src/prov.py
If git2prov node module is not installed, prov is not created on spec.
=> Make git2prov optional

requirements.txt, src/fileLoaders.py, src/gquery.py, src/projection.py, src/prov.py, src/server.py, src/sparql.py, src/static.py, src/swagger.py, src/utils.py, tests/mock_data.py, tests/test_gquery.py, tests/test_projection.py, tests/test_swagger.py
New feature, [discussed long ago](https://github.com/SparqlProjections/TestSuite) this PR adds the possibility of adding *projections* for JSON results. This gives the user the possibility of providing a pythonql script which will transform the JSON coming from the triplestore into a different format.
An [example repo](https://github.com/c-martinez/grlc-queries) is provided. Query `dbpediaCapitalsLocation` fetches from dbpedia location of country capitals. `dbpediaCapitalsLocation.pyql` transforms the result to a GeoJSON file.
Calling this endpoint
```curl -X GET "http://localhost:8088/api/c-martinez/grlc-queries/dbpediaCapitalsLocation" -H "accept: application/json"```
Would usually return something like this:
```json
{
"head": {
"link": [],
"vars": [
"country_name",
"capital_name", …
```
=> Support for JSON projections

.gitignore, requirements.txt, src/gquery.py, tests/repo/test-json.json, tests/repo/test-sparql-jsonconf.sparql, tests/test_gquery.py
The decorator can now be written both in YAML or JSON.
Moreover `pyaml` has been updated for avoiding deprecation (sopping to work in python 3.8)
=> configuration in json

requirements.txt, src/utils.py, tests/mock_data.py, tests/repo/test-projection.rq, tests/test_gquery.py, tests/test_loaders.py, tests/test_utils.py
Implementing functionality discussed in #215 (requires the freshly released `SPARQLTransform==1.7.0`)
SPARQLTransform syntax can be included in the grlc decorator header `transform`. Response will be transformed according to that syntax, while query can still be SPARQL and keep he full expressiveness of SPARQL.
I think we can get rid of the old pyql projections (of which I think I was the only user) and of the json query syntax. What do you think @albertmeronyo & @pasqLisena ?
=> Project transform

src/server.py, src/static/js/grlc-api.js, src/templates/api-docs.html, src/templates/index.html
This should fix issues when grlc runs behind on a sub-path (and not on the server root path)
=> Use relative paths for swagger spec

README.md
Parameter mapping was not really documented on the README.
This fixes #279 -- thanks @CunliangGeng for spotting this!
=> Document parameter mapping

src/server.py
A bug in the `<subdir>` parameter mapping caused it to be ignored when building API's such as `http://grlc-server/api-git/<user>/<repo>/subdir/<subdir>`. This PR addresses this issue.
=> Fix <subdir> bug

tests/mock_data.py, tests/test_gquery.py, tests/test_utils.py
Fixes #176 
Paths checked
`/api-git/testuser/testrepo`
`/api-git/testuser/testrepo/subdir/<subdir>`
`/api-git/testuser/testrepo/commit/<sha>`
`/api-git/testuser/testrepo/subdir/<subdir>/commit/<sha>`
`/api-local/`
`/api-url/?specUrl=<specUrl>`
`/api-git/testuser/testrepo/swagger`
`/api-git/testuser/testrepo/subdir/<subdir>/swagger`
`/api-git/testuser/testrepo/commit/<sha>/swagger`
`/api-git/testuser/testrepo/subdir/<subdir>commit/<sha>/swagger`
`/api-local/swagger`
`/api-url/swagger?specUrl=<specUrl>`
`/api-git/testuser/testrepo/<query_name>`
`/api-git/testuser/testrepo/subdir/<subdir>/<query_name>`
`/api-git/testuser/testrepo/commit/<sha>/<query_name>`
`/api-git/testuser/testrepo/subdir/<subdir>commit/<sha>/<query_name>`
`/api-local/<query_name>`
`/api-url/<query_name>?specUrl=<specUrl>` …
=> Path testing

doc/notebooks/GrlcFromNotebook.ipynb, src/swagger.py, src/utils.py, tests/test_grlc.py, tests/test_swagger.py
This PR adds the following functionality:
When grlc is not able to generate an API endpoint from a `*.rq` file, a warning is generated. These warnings are then displayed in the swagger API.
This fixes #168
=> Warning prefixes

README.md, src/server.py
This functionality was already implemented for `/api-git` paths, but not for `/api-local` and `/api-url`. This PR adds this extra functionality. 
Fixes #304
=> Control results format by adding a file extension

.travis.yml
Actually were only using 3.5 functionality for testing.
Fixes #303
=> Remove 3.5 support

src/utils.py
When a prefix is missing on the query, an internal server error is raised. This PR manages this more gracefully.
This PR and #315 both address issues raised when executing a query. Perhaps we should merge them and have a more elegant way to handle query execution issues.
=> Handle errors raised by missing prefix

src/swagger.py
For queries displayed in the detail of swagger-ui, the first line of the query is being removed (commented out). 
For example this query:
```
#+ summary: Returns the bands
#+ endpoint: http://dbpedia.org/sparql
PREFIX dbo: <http://dbpedia.org/ontology/>
SELECT ?band WHERE {
?band a dbo:Band .
?band dbo:genre ?__genre_iri .
} 
LIMIT 30
```
Is displayed like this (`summary` is missing):
This PR fixes this issue.
=> Fix query display in summary

requirements.txt
Manually implementing dependency updates from https://github.com/CLARIAH/grlc/pull/323
=>  Bump pyyaml from 4.2b1 to 5.4

.travis/install.sh, .zenodo.json, CITATION.cff, CONTRIBUTORS.md, requirements.txt
This release includes:
- Update documentation & contributing guidelines
- Update requirements (docutils)
- Add format control via extension (thanks @ecow for reporting)
- Remove 3.5 support
- Remove support for `/spec` in favour of `/swagger`
- Restrict transform decorator to application/json (thanks @ecow for reporting)
- Catching exception connecting to SPARQL endpoint
- Handle errors raised by missing prefix
- Fix query display in summary
- Upgrade SPARQL transformer to support list objects (thanks @rapw3k for suggesting this feature and @pasqLisena for implementing it)
=> Preparing for 1.3.6 release

src/swagger.py
Following from discussion from #330, adding a warning if license is not present.
=> Add a warning if license is not found

.github/workflows/testing.yml, requirements.txt
Tested for Pythons 3.6.15 | 3.7.16 | 3.8.16 | 3.9.16 as follows:
```bash
virtualenv py3X --python python3X
source py3X/bin/activate
pip install .
pip install -r requirements-test.txt
pytest tests/
deactivate
```
(where the X is the python version 6, 7, 8 or 9)
=> Pip installable up to python 3.9

README.md, src/fileLoaders.py, src/queryTypes.py
=> Extended yaml API specification

README.md
JOSS submission was accepted a while ago, but we never got around to adding a badge for it in the README.
=> Add JOSS badge

config.default.ini, requirements.txt, src/fileLoaders.py, src/server.py, src/static.py, src/swagger.py, src/utils.py, tests/mock_data.py, tests/test_grlc.py, tests/test_loaders.py, tests/test_swagger.py
Continuing here from #387
A few issues that remain:
- Method [dispatch_query](https://github.com/CLARIAH/grlc/compare/master...Orange-OpenSource:grlc:master#diff-843cf1395093d42946cea4b5b53f687c535a7bd94d358b2c59e8f3e5a18d830aR201-R229) seems to be significantly different. It looks like it just posts request directly to the endpoint, without rewriting the query (which, we want to do), so I am sticking to the original implementation (unless I am missing something somewhere)
- Variable `git_type` is used to differentiate between GitHub and GitLab loaders. It is assigned `"github"` and `"gitlab"` -- it should probably be replaced for a constant.
- Tests for gitlab are missing
=> Manually incorporatig Gitlab support

README.md
We moved away from Travis, to testing on GH actions, but the badge in README was outdated.
=> Add badge for testing with GitHub actions

requirements.txt
Dependabot recommended upgrading requests, but automatic PR are based on `master`. I think will make PRs go to `dev`  #410, but in the meantime, this PR manually implements #401.
=> Bumping requests version

README.md, src/utils.py, tests/repo/test-endpoint-get.rq, tests/test_loaders.py, tests/test_utils.py
As suggested by @tkuhn in https://github.com/CLARIAH/grlc/commit/b09824ab3673cb34b2400b78d275f512d0d1a43c. 
Adds a new decorator: `endpoint-method` which can be set to `POST` or `GET` (default `POST`). This allows to control the HTTP method used to communicate between the grlc server and the SPARQL endpoint. According to https://www.w3.org/TR/sparql11-protocol/, both GET and POST are supported.
=> Adds endpoint-method decorator

requirements.txt
I recently found out that `docopt` is no longer maintained (last update was 2014, see https://github.com/docopt/docopt/issues/519). Fortunately a fork project seems to be actively maintained: https://github.com/jazzband/docopt-ng
This PR migrates from `docopt` to `docopt-ng`.
=> Docopt dead

README.md
A few months ago, my (now-ex) colleague @jspaaks worked on creating a [tool for self-assessment of FAIRness](https://www.esciencecenter.nl/news/new-self-assessment-tool-to-promote-fair-research-software/) of research software. I created an issue (#383) to assess FAIRness of grlc. Now that the tool has been released, we should include the badge on the readme.
This PR adds the badge of grlc FAIRness assessment to the README.
=> Add FAIRness badge from eScience/ARDC checklist

.github/dependabot.yml
Changing dependabot to ignore patches and only apply major or minor updates.
=> Ignore patches on dependabot

src/gquery.py, src/swagger.py, src/utils.py, tests/mock_data.py, tests/test_grlc.py, tests/test_swagger.py
Adds a check to make sure JSON files in a repository are valid for SPARQLTransformer, and can be processed as queries to generate API endpoints. If a JSON file is not a valid query, it will  be ignored.
Addresses #481
=> Transformer json check

README.md
Adds a small mention of Query in JSON syntax support.
Not sure if this is enough,  or if there are better documentation resources we could point to.
Addresses #482.
=> Add a mention of query-in-json support

config.default.ini
Makes https://gitlab.com be the default gitlab instance used in config.ini (in the config.default.ini file provided)
Fixes #486
=> Add gitlab.com as default in config.ini
